### ISSUE TITLE
Adjust home screen

### ISSUE THREAD

**Issue by Frezeyx** [Dopaemin/MindeshapeIOS#3]
Adjust home screen

- [ ] delete tip of the week
- [ ] adjust screen that it does not seem empty

**Comment by Dopaemin** [comment]
![Screenshot 2022-05-19 at 20 46 04](https://user-images.githubusercontent.com/84579304/169376971-0acf399c-bbdc-4a37-88e8-60a7e8f5debe.png)

Fixed. Dynamically with every iPhone Size. Some Space on the big Phones, but feature will fill this in Future.
